//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScenarioTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PL.Properties.ScenarioTexts", typeof(ScenarioTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no events..
        /// </summary>
        public static string HasNoEvents {
            get {
                return ResourceManager.GetString("HasNoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not lots of rules. All that you must know: You have 100 AM$ at the beginning of the game..
        /// </summary>
        public static string InstructionsPoint1 {
            get {
                return ResourceManager.GetString("InstructionsPoint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this city you will be go along streets and have meetings with different members of local guilds..
        /// </summary>
        public static string InstructionsPoint2 {
            get {
                return ResourceManager.GetString("InstructionsPoint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read guidance closely as the game progresses. And my advice for you : Try to survive as long as possible..
        /// </summary>
        public static string InstructionsPoint3 {
            get {
                return ResourceManager.GetString("InstructionsPoint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTRUCTIONS.
        /// </summary>
        public static string InstructionsTitle {
            get {
                return ResourceManager.GetString("InstructionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You go along the streets of Ankh-Morpork and ....
        /// </summary>
        public static string WalkingMessage {
            get {
                return ResourceManager.GetString("WalkingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ankh-Morpork lies on the River Ankh (the most polluted waterway on the Discworld and reputedly solid enough to walk on), where the fertile loam of the Sto Plains meets the Circle Sea. This, naturally, puts it in an excellent trading position. The central city divides more or less into Ankh (the posh part) and Morpork (the humble part, which includes the slum area known as &quot;the Shades&quot;), which are separated by the River Ankh..
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the fine city of Ankh-Morpork!.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can be dangerous to walk the streets. So watch out!.
        /// </summary>
        public static string WelcomeWarningMessage {
            get {
                return ResourceManager.GetString("WelcomeWarningMessage", resourceCulture);
            }
        }
    }
}
