//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NpcsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NpcsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.Properties.NpcsResources", typeof(NpcsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but no one could take your contract..
        /// </summary>
        public static string AssassinKillsPlayerPostscript {
            get {
                return ResourceManager.GetString("AssassinKillsPlayerPostscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassins&apos; Guild.
        /// </summary>
        public static string AssassinsGuild {
            get {
                return ResourceManager.GetString("AssassinsGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s just an assassin&apos;s job..
        /// </summary>
        public static string AssassinsLoseGamePostscript {
            get {
                return ResourceManager.GetString("AssassinsLoseGamePostscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... Someone signed a contract to kill you. If you wanna survive and go on to enjoy your life, you must pay. Accept to cooperate with us, enter a random fee and we try to find an assassin to kill your enemy. If you skip, so... Our member will have fulfilled a contract out on you..
        /// </summary>
        public static string AssassinsWelcomeMessage {
            get {
                return ResourceManager.GetString("AssassinsWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, beggars don&apos;t forgive deeds like this..
        /// </summary>
        public static string BeggarKillsPlayerPostscript {
            get {
                return ResourceManager.GetString("BeggarKillsPlayerPostscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beggars&apos; Guild.
        /// </summary>
        public static string BeggarsGuild {
            get {
                return ResourceManager.GetString("BeggarsGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, donate some money.. Save your soul. Accept to donate a fix sum of money and make a good deed. Or if you skip us, you will chase you to death....
        /// </summary>
        public static string BeggarsWelcomeMessage {
            get {
                return ResourceManager.GetString("BeggarsWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fools&apos; Guild.
        /// </summary>
        public static string FoolsGuild {
            get {
                return ResourceManager.GetString("FoolsGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s strange. You lost easy money. *These players, sometimes, are so illogical..
        /// </summary>
        public static string FoolsLoseGame {
            get {
                return ResourceManager.GetString("FoolsLoseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our congratulations! You earned some money.But remember, you have to pretend to be a fool, as your friend.
        /// </summary>
        public static string FoolsPlayGamePrescript {
            get {
                return ResourceManager.GetString("FoolsPlayGamePrescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! I&apos;m your friend in Ankh-Morpork! Accept to earn some money in this city. If you skip, you get nothing. .
        /// </summary>
        public static string FoolsWelcomeMessage {
            get {
                return ResourceManager.GetString("FoolsWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lack of beer is sometimes fatal..
        /// </summary>
        public static string PlayerIsLackOfBeerPostscript {
            get {
                return ResourceManager.GetString("PlayerIsLackOfBeerPostscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, you didn&apos;t have enough money to donate..
        /// </summary>
        public static string PlayerIsLackOfMoneyPostscript {
            get {
                return ResourceManager.GetString("PlayerIsLackOfMoneyPostscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, my dear friend!.
        /// </summary>
        public static string PlayerIsNotLackOfBeerPostscript {
            get {
                return ResourceManager.GetString("PlayerIsNotLackOfBeerPostscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You donated some money. Good deeds come back like a boomerang. Therefore, live on..
        /// </summary>
        public static string PlayerWinsBeggar {
            get {
                return ResourceManager.GetString("PlayerWinsBeggar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s a result of thieves&apos; codex..
        /// </summary>
        public static string ThiefKillsPlayerPostscript {
            get {
                return ResourceManager.GetString("ThiefKillsPlayerPostscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thieves&apos; Guild.
        /// </summary>
        public static string ThievesGuild {
            get {
                return ResourceManager.GetString("ThievesGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, you didn&apos;t have enough money to pay off the Thieves&apos; Guild..
        /// </summary>
        public static string ThievesLoseGamePostscript {
            get {
                return ResourceManager.GetString("ThievesLoseGamePostscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey! How&apos;s it going? Do you have something in your pockets? Accept to pay off us and loose 10 AM$. If you don&apos;t wanna pay, you will be died. Such rules....
        /// </summary>
        public static string ThievesWelcomeMessage {
            get {
                return ResourceManager.GetString("ThievesWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownName {
            get {
                return ResourceManager.GetString("UnknownName", resourceCulture);
            }
        }
    }
}
